### ISSUE TITLE
Create business description 

### ISSUE THREAD

**Issue by wllngr** [bitsass/taskmanagement#18]

**Comment by bitsass** [comment]
Looking for clarification.  Do we want to take an existing customer, an ideal customer, a customer in six months?

**Comment by wllngr** [comment]
None, it's not so much customer focused as much as a high level overview of what we do. Essentially the executive overview of the product breakdown with a concept for application. 
e.g. we provide a node.js backend system, data mining services, and consulting for IT/business solutions. 
I'd like to put this into a couple paragraphs that would explain to an investor what we do and why.
