### ISSUE TITLE
Store Crawls Automatically on Crawl.go() and Crawl.setup()

### ISSUE THREAD

**Issue by bitsass** [bitsass/taskmanagement#30]
Related to #23.

In addition to storing state of crawl as it runs, the Crawl Page's and Field's themselves should be serialized and stored.  Additionally, the Crawl.setup function which usually gathers links should be stored.

**Comment by briancappello** [comment]
One thing I thought of was what if `go` returned a Promise (that resolved to the crawl's results)? I would think that should at least allow chaining crawls
