### ISSUE TITLE
Merge 14.04 shell script to 16.04 Docker Image, grabbing LAMP + Node.js for now

### ISSUE THREAD

**Issue by bitsass** [bitsass/taskmanagement#57]
See https://bitbucket.org/sassworks/servermanager/src/master/deploy/archive/ubuntu-14.04-setup.sh

and in theory we want to pull in LAMP and Node.js for now into the 16.04 Docker image found here:
https://bitbucket.org/sassworks/servermanager/src/master/src/ubuntu-16.04/DockerFile

there is some pain in that you have to utilize options to disable keyboard input prompts.  additionally there are some breaks/differences in 16.04.  besides this, there was some environment setup needed IIRC to get just the XFCE and VNC server up and going.

**Comment by briancappello** [comment]
@mikegwhit What do you think of using [this](https://github.com/fauria/docker-lamp) as a starting point? It's based on 16.04, PHP7, mariadb, and apache, includes node, and doesn't use docker-compose, instead opting for running all of the services in a single container. I'll fuck around with trying to add phpmyadmin to it.
